-- This file should undo anything in `up.sql`

DROP TABLE IF EXISTS slides CASCADE;
DROP TABLE IF EXISTS assets_objects CASCADE;
DROP TABLE IF EXISTS capsules_projects CASCADE;
DROP TABLE IF EXISTS capsules CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS asset_type CASCADE;
DROP TYPE IF EXISTS published_type CASCADE;
